### PR TITLE
upgrade to grpc 1.2.0 everywhere

### PR DESCRIPTION
**Pull request by danielamiao**

### CODE REVIEW

**Comment by joeblubaugh** [comment]
Is the bug that part of GRPC was on 1.2 and parts were still on 1.1.0?

Can we group these in the dependency block or use a variable so that they're kept in sync?

**Comment by danielamiao** [comment]
yeah one of the test dependencies was still on 1.1.1 - there are 3 separate build.gradle files "common" , "jre" and "android" so can't group them together, might be possible to use a variable as you suggested, I'll look into it (though it'll go away once we split these repos)

**Comment by joeblubaugh** [comment]
I think it's reasonable to have separate variables in each build file, or just be cognizant of this problem. Exporting these values from an inner dependency out is likely to be a mess.

**Comment by danielamiao** [comment]
Sounds good - it's good practice to convert all version literals into variables and group them together in each build.gradle file, I'll also add a comment next to the GRPC version (to remind us that the versions likely need to be synced across the 3 files)

**Pull request merged**
