### PR TITLE
Merge grpc-dev branch to master

### PR DESCRIPTION
**Pull request by danielamiao**
There is nothing new here that you haven't reviewed already - just more of a formality in case there are any last lingering concerns before we publish this. Will also send out to team.

### CODE REVIEW

**Comment by bensigelman** [comment]
@danielamiao since the code has already been reviewed, I'm not concerned with that bit – my only question pertains to artifacts and publishing. Even though there are no API changes, I think we should bump the minor version just in case there are people auto-upgrading patch versions and there turns out to be an unforeseen compatibility issue.

Other than that: well done and thanks again!

**Comment by nimeshksingh** [comment]
Sorry, I haven't been paying attention, but I figure this may be a good time to ensure that the 'guids' (reporterid, traceid, spandid, parentspanid, etc.) are all being created the way the collectors want.  They expect the equivalent of go uint64s.  This was broken in some way in Thrift, and seems likely to be fixed in your grpc version, but I'll try to confirm by the time you want to publish it.

**Comment by danielamiao** [comment]
@bensigelman Sounds good! I agree the version bump is needed, I'm going to elicit help from @frenchfrywpepper on Monday since she did a great job with the gradle publish scripts, we will go from current version (0.10.1) to 0.10.2.

@nimeshksingh Good call, thanks for the reminder. I double checked the proto file from which the classes are generated and everything is defined as uint64 (https://github.com/lightstep/lightstep-tracer-common/blob/master/collector.proto). I also did run both JRE and Android sample apps by sending spans to collector-grpc-staging and the traces showed up correctly so I think we are all good there!

**Comment by bensigelman** [comment]
> we will go from current version (0.10.1) to 0.10.2.

That would happen just be re-running the publish script... I'd strongly suggest calling this `0.11.0` since it's a big change from an impl standpoint and I want users to opt-in to it. I realize that this is a little funky from a semver standpoint, but I think it's "spiritually" in line with the idea of semver (that patch releases are only making things more stable).

**Comment by danielamiao** [comment]
Ah, OK that makes sense, I misunderstood "minor version" before. Sounds good will manually update the version to 0.11.0 when publishing on Monday.

**Comment by nimeshksingh** [comment]
K, LGTM re: guids

**Pull request merged**
